# Generated by Django 3.1.3 on 2021-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0026_auto_20210702_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubntmodeltest',
            name='ubntlogin',
            field=models.CharField(default='ubnt', max_length=50, verbose_name='Логин для входа в РРС (Для локалной и удалённой РРС)'),
        ),
        migrations.AddField(
            model_name='ubntmodeltest',
            name='ubntpassword',
            field=models.CharField(default='ubnt', max_length=50, verbose_name='Пароль для входа в РРС (Для локальной и удалённой РРС'),
        ),
    ]
