# Generated by Django 3.1.3 on 2021-12-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0028_remove_ubntmodeltest_distributed_system_onoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubntmodeltest',
            name='rrsflag',
            field=models.IntegerField(default=0, verbose_name='Если "0" - это РРС AirFiber 11, Если "1" - это РРС Alcoma'),
        ),
    ]
