# Generated by Django 3.1.3 on 2022-01-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0030_ubfail_ubsuccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUbntalways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipubnttwo', models.CharField(max_length=50, verbose_name='IP-адрес локальной РРС')),
                ('ipubnttworem', models.CharField(max_length=50, verbose_name='IP-адрес удалённой РРС полученный из JSON')),
                ('udprml0', models.IntegerField(verbose_name='Уровень приёма(0) локальной РРС полученный из JSON')),
                ('udprml1', models.IntegerField(verbose_name='Уровень приёма(1) локальной РРС полученный из JSON')),
                ('udprmr0', models.IntegerField(verbose_name='Уровень приёма(0) удалённой РРС полученный из JSON')),
                ('udprmr1', models.IntegerField(verbose_name='Уровень приёма(1) удалённой РРС полученный из JSON')),
                ('udspeedl', models.FloatField(verbose_name='Ёмкость приёма локальной РРС полученный из JSON')),
                ('udspeedr', models.FloatField(verbose_name='Ёмкость приёма удалённой РРС полученный из JSON')),
                ('detail_txt', models.CharField(max_length=5000)),
                ('timewrite', models.DateTimeField(auto_now_add=True, verbose_name='Записано')),
            ],
            options={
                'verbose_name': 'Уровень приёма локальной РРС',
                'verbose_name_plural': 'Уровень приёма локальной РРС',
                'ordering': ['-timewrite'],
            },
        ),
    ]
