# Generated by Django 3.1.3 on 2022-01-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0031_dataubntalways'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUbntonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipubnttwo', models.CharField(max_length=50, verbose_name='IP-адрес локальной РРС')),
                ('detail_txt', models.CharField(max_length=5000)),
                ('timewrite', models.DateTimeField(auto_now_add=True, verbose_name='Записано')),
            ],
            options={
                'verbose_name': 'Детальная информация по настройкам РРС',
                'verbose_name_plural': 'Детальная информация по настройкам РРС',
                'ordering': ['-timewrite'],
            },
        ),
        migrations.RemoveField(
            model_name='dataubntalways',
            name='detail_txt',
        ),
    ]
